"""Authenticity: the symbolic spec must reproduce the frozen golden vectors generated by the
reference implementations' actual running code (see golden/generate/ for provenance).

Derivative vectors check the continuous model f(s,u,θ) directly; step vectors additionally
check the discretizations (fixed-step RK4, exact-exp motor splitting) plus the harness-side
post-step operations the reference applies (quaternion renormalization, rotor-speed clipping),
which are replicated here explicitly."""

import json
import pathlib

import numpy as np
import pytest

from spec.discretization import rk4_step
from properties.helpers import N, flat_params, statedot_fn

VECTOR_DIR = pathlib.Path(__file__).resolve().parent.parent / "golden" / "vectors"
FILES = sorted(VECTOR_DIR.glob("*.json"))


def _load(path):
    return json.loads(path.read_text())


def _flat_state(c):
    st = c["state"]
    return np.concatenate([st["x"], st["v"], st["q_wxyz"], st["w"], st["rotor_speeds"]])


def _flat_inputs(c):
    i = c["inputs"]
    return np.concatenate([i["cmd_rotor_speeds"], i["v_wind"], i["F_ext"], i["tau_ext"]])


def _params(doc):
    vals = {k: v for k, v in doc["params"].items() if k != "limits"}
    return flat_params(vals)


def _check(got, expected, context):
    scale = max(1.0, np.abs(expected).max())
    np.testing.assert_allclose(got, expected, rtol=1e-9, atol=1e-9 * scale,
                               err_msg=context)


@pytest.mark.parametrize("path", FILES, ids=lambda p: p.stem)
def test_golden(path):
    doc = _load(path)
    p = _params(doc)
    f = statedot_fn(doc.get("motor_model", "first_order"))
    kind = doc["kind"]
    lim = doc["params"]["limits"]

    for k, c in enumerate(doc["cases"]):
        s = _flat_state(c)
        u = _flat_inputs(c)
        e = c["expected"]
        ctx = f"{path.stem} case {k}"

        if kind == "statedot":
            expected = np.concatenate([e["xdot"], e["vdot"], e["qdot_wxyz"], e["wdot"],
                                       e["Wdot"]])
            _check(f(s, u, p), expected, ctx)
            continue

        dt = doc["dt"]
        if kind == "step_ode":
            s_next = rk4_step(lambda t, x: f(x, u, p), s, dt)
        elif kind == "step_exact_exp":
            # Operator split: rotor speed follows the closed form at stage times, its ODE slot
            # is held; after the step it is set to Ω(dt) analytically.
            tau = doc["params"]["tau_m"]
            W0, Wc = s[13:13 + N], u[:N]

            def f_split(t, x):
                x = x.copy()
                x[13:13 + N] = Wc + (W0 - Wc) * np.exp(-t / tau)
                out = f(x, u, p)
                out[13:13 + N] = 0.0
                return out

            s_next = rk4_step(f_split, s, dt)
            s_next[13:13 + N] = Wc + (W0 - Wc) * np.exp(-dt / tau)
        else:
            raise AssertionError(f"unknown kind {kind}")

        # Reference harness post-step: renormalize quaternion, clip rotor speeds.
        s_next[6:10] /= np.linalg.norm(s_next[6:10])
        s_next[13:13 + N] = np.clip(s_next[13:13 + N],
                                    lim["rotor_speed_min"], lim["rotor_speed_max"])
        expected = np.concatenate([e["x"], e["v"], e["q_wxyz"], e["w"], e["rotor_speeds"]])
        _check(s_next, expected, ctx)


def test_vectors_present():
    assert len(FILES) >= 12, "golden vector set incomplete"
